name: Automated JMeter Tests

# Define triggers
on: 
  # Manual workflow trigger with input parameters
  workflow_dispatch:
    inputs:
      users:
        description: 'Number of users (threads)'
        required: true
        type: choice
        options: 
          - 1
          - 5
          - 10
          - 20
          - 50
        default: 1
      ramp_up:
        description: 'Ramp-up period (seconds)'
        required: true
        type: choice
        options: 
          - 1
          - 5
          - 10
          - 20
          - 30
        default: 1

  # Automatically trigger on push to specific branches
  push:
    branches: 
      - demo_blaze  # Run tests automatically when code is pushed to 'demo_blaze'

  # Schedule the workflow to run every 5 minutes
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes

jobs:
  automated-jmeter-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JMeter
        run: choco install jmeter -y  # Use Chocolatey to install JMeter on Windows

      - name: Check JMeter Version
        run: jmeter -v  # Verify JMeter installation and version

      - name: Run JMeter Tests
        run: |
          jmeter -n -t scripts/DemoBlaze.jmx -Jusers=${{ github.event.inputs.users }} -Jramp_up=${{ github.event.inputs.ramp_up }} -l results/result.jtl -e -o html -j results/jmeter.log

      - name: List Results Directory
        run: |
          echo "Listing results directory:"
          dir results  # Use 'dir' to list the contents of results folder in Windows

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results/result.jtl

      - name: Upload JMeter Log
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-log
          path: results/jmeter.log

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: html  # This uploads the entire HTML report folder
          if-no-files-found: error
